images_paths = {
    "dish_kosashorva": "images/Kosa sho'rva.jpg",
    "dish_dumbullidimlama": "images/Dumbulli dimlama.jpg",
    "dish_piyozlishorva": "images/Piyozli shorva.jpg",
    "dish_suyuqnorin": "images/Suyuq norin.jpg",
    "dish_uygurlagmon": "images/Uygur lagmon.jpg",
    "dish_moxora": "images/Moxora.jpg",
    "dish_goja": "images/Go'ja.jpg",
    "dish_lagmon": "images/Lagmon.jpg",
    "dish_sabzavotd": "images/Sabzavotli dolma.jpg",
    "dish_mantilishorva": "images/Mantili shorva.jpg",
    "dish_firkadelkali": "images/Firkadelkali shorva.jpg",
    "dish_kosadimlama": "images/Kosa dimlama.jpg",
    "dish_tuxumdolma": "images/Tuxum dolma.jpg",
    "dish_mastava": "images/Mastava.jpg",
    "dish_chuchvara": "images/Chuchvara.jpg",
    "dish_andijonmanti": "images/Andijon manti.jpg",
    "dish_spagetti": "images/Spagetti.jpg",
    "dish_qovurmala": "images/Qovurma lag'mon.jpg",
    "dish_dimlama": "images/Dimlama.jpg",
    "dish_beshbarmoq": "images/Besh barmoq.jpg",
    "dish_bibimbap": "images/Bibimbap.jpg",
    "dish_quyuqdolma": "images/Do'lma.jpg",
    "dish_choyxona": "images/Choyxona palov.jpg",
    "dish_gulxonim": "images/Gulxonim.jpg",
    "dish_bayramona": "images/Bayramona osh va ayron.jpg",
    "dish_grechkapalov": "images/Grechka palov.jpg",
    "dish_turkcharatatuy": "images/Turkcha ratatuy.jpg",
    "dish_balish": "images/Balish.jpg",
    "dish_goshlirulet": "images/Go'shli rulet.jpg",
    "dish_shivit": "images/Shivit oshi.jpg",
    "dish_nonpalov": "images/Non palov.jpg",
    "dish_kartoshkadolma": "images/Kartoshka do'lma.jpg",
    "dish_dumbulpalov": "images/Dumbul palov.jpg",
    "dish_teftel": "images/Teftel.jpg",
    "dish_sarimsoqli": "images/Sarimsoqli kartoshka.jpg",
    "dish_begodi": "images/Begodi.jpg",
    "dish_baliqlikotlet": "images/Baliqli kotlet.jpg",
    "dish_jigarkabob": "images/Jigar kabob.jpg",
    "dish_qozonkabob": "images/Qozon kabob.jpg",
    "dish_qiymalikabob": "images/Qiymali kabob.jpg",
    "dish_tandirkabob": "images/Tandir kabob.jpg",
    "dish_tovuqkabob": "images/Tovuq kabob.jpg",
    "dish_namangankabob": "images/Namangan kabob.jpg",
    "dish_norin": "images/Norin.jpg",
    "dish_xasip": "images/Xasip.jpg",
    "dish_tuxumbarak": "images/Tuxum Barak.jpg",
    "dish_achchiqchuchuk": "images/Achchiqchuchuksalat.jpg",
    "dish_bodringbrinza": "images/Bodring va brinzali salat.jpg",
    "dish_karampomidor": "images/Karam va pomidorli salat.jpg",
    "dish_gruzincha": "images/Gruzincha salat.jpg",
    "dish_qarsildoq": "images/Qarsildoq salat.jpg",
    "dish_suzmali": "images/Suzmali salat.jpg",
    "dish_penchuza": "images/Penchuza salat.jpg",
    "dish_mandarin": "images/Mandarin salat.jpg",
    "dish_tovuqlisalat": "images/Tovuqli salat.jpg",
    "dish_smak": "images/Smak salat.jpg",
    "dish_ozdiruvchi": "images/Ozdiruvchi salat.jpg",
    "dish_mevali": "images/Mevali salat.jpg",
    "dish_braslet": "images/Braslet salat.jpg",
    "dish_qotgannonli": "images/Qotgan nonli salat.jpg",
    "dish_goshtlisa": "images/Go'shtli salat.jpg",
    "dish_karamli": "images/Karamli salat.jpg",
    "dish_olivye": "images/Olivye.jpg",
    "dish_tovuqiolivye": "images/Tovuqli olivye.jpg",
    "dish_bodringsalat": "images/Bodring salat.jpg",
    "dish_shanxay": "images/Shanxaycha salat.jpg",
    "dish_qushuyali": "images/Qush uyali salat.jpg",
    "dish_toshkentsalat": "images/Toshkentcha salat.jpg",
    "dish_portobello": "images/Portobello salat.jpg",
    "dish_ananas": "images/Ananas va tovuqli salat.jpg",
    "dish_sezar": "images/Sezar salat.jpg",
    "dish_bodringkaram": "images/Bodring va karamli salat.jpg",
    "dish_turkchaburek": "images/Turkcha burek.jpg",
    "dish_goshtlisomsa": "images/Go’shtli somsa.jpg",
    "dish_yupqa": "images/Yupqa.jpg",
    "dish_qiymaliquymoq": "images/Qiymali quymoq.jpg",
    "dish_pishloqlicheburek": "images/Pishloqli cheburek.jpg",
    "dish_gumma": "images/Gumma.jpg",
    "dish_pahlava": "images/Pahlava.jpg",
    "dish_chakchak": "images/Chak-chak.jpg",
    "dish_turkchapishiriq": "images/Turkcha pishiriq.jpg",
    "dish_qozonsomsa": "images/Qozon somsa.jpg",
    "dish_sabzavotlisomsa": "images/Sabzavotli somsa.jpg",
    "dish_yuraksomsa": "images/Yurak somsa.jpg",
    "dish_qatlamasomsa": "images/Qatlama somsa.jpg",
    "dish_nisholda": "images/Nisholda.jpg",
    "dish_holvetar": "images/Holvetar.jpg",
    "dish_tvaroglikr": "images/Tvaroglikrendel.jpg",
    "dish_shokoglazur": "images/Shokoladli glazur.jpg",
    "dish_bananlieskimo": "images/Bananli eskimo.jpg",
    "dish_jemlipirog": "images/Jemli pirog.jpg",
    "dish_tvoroglibulochka": "images/Tvaroglibulochka.jpg",
    "dish_malinalichizkeyk": "images/Malinali chizkeyk.jpg",
    "dish_bolqaymoq": "images/Bolqaymoq.jpg",
    "dish_murabbolipirog": "images/Murabboli pirog.jpg",
    "dish_asallipirojniy": "images/Asalli pirojniy.jpg",
    "dish_shaftolilimizq": "images/Shaftolili muzqaymoq.jpg",
    "dish_aylanay": "images/Aylanay pirogi.jpg",
    "dish_chumoliuya": "images/Chumoli uyasi.jpg",
    "dish_olchali": "images/Olchali pirog.jpg",
    "dish_shokokeks": "images/Shokoladli keks.jpg",
    "dish_asallipechenye": "images/Asalli pechenye.jpg",
    "drink_olmali": "images/Olmali choy.jpg",
    "drink_namatak": "images/Namatak sharbati.jpg",
    "drink_yalpizlimon": "images/Yalpizli limon choy.jpg",
    "drink_qulupnay": "images/Qulupnayli ichimlik.jpg",
    "drink_qovun": "images/Qovun sharbati.jpg",
    "drink_bodomli": "images/Bodomli sut.jpg",
    "drink_uzum": "images/Uzum sharbati.jpg",
    "drink_mevali": "images/Mevali sharbat.jpg",
    "drink_qatiq": "images/Qatiq.jpg",
    "drink_tarvuz": "images/Tarvuz sharbati.jpg",
    "drink_sabzi": "images/Sabzi sharbati.jpg",
    "drink_zira": "images/Zira choy.jpg",
    "drink_vitaminli": "images/Vitaminli ichimlik.jpg",
    "drink_moxito": "images/Moxito.jpg",
    "tort_praga": "images/Praga torti.jpg",
    "tort_napaleon": "images/Napaleon torti.jpg",
    "tort_zebra": "images/Zebra torti.jpg",
    "tort_pancho": "images/Pancho torti.jpg",
    "tort_medovik": "images/Medovik torti.jpg",
    "tort_frezye": "images/Frezye torti.jpg",
    "tort_karamel": "images/Karamel torti.jpg",
    "tort_kitakat": "images/Kita-kat torti.jpg",
    "tort_boston": "images/Bostoncha kremli tort.jpg",
    "tort_bounty": "images/Bounty torti.jpg",
    "tort_pavlova": "images/Pavlova torti.jpg",
    "non_qatlamapatir": "images/Qatlama patir.jpg",
    "non_shirinkulcha": "images/Shirin kulcha.jpg",
    "non_moychechak": "images/Moychechak non.jpg",
    "non_goshtli": "images/Go’shtli non.jpg",
    "non_patir": "images/Patir.jpg",
    "non_lochira": "images/Lochira patir.jpg",
    "non_obinon": "images/Obi non.jpg",
    "non_qatlama": "images/Qatlama.jpg",
    "non_jizzali": "images/Jizzali patir.jpg"
}
