images_paths = {
    "dish_kosashorva": r"C:\Users\kursu\Downloads\Telegram Desktop\Kosa sho'rva.jpg",
    "dish_dumbullidimlama": r"C:\Users\kursu\Downloads\Telegram Desktop\Dumbulli dimlama.jpg",
    "dish_piyozlishorva": r"C:\Users\kursu\Downloads\Telegram Desktop\Piyozli shorva.jpg",
    "dish_suyuqnorin": r"C:\Users\kursu\Downloads\Telegram Desktop\Suyuq norin.jpg",
    "dish_uygurlagmon": r"C:\Users\kursu\Downloads\Telegram Desktop\Uygur lagmon.jpg",
    "dish_moxora": r"C:\Users\kursu\Downloads\Telegram Desktop\Moxora.jpg",
    "dish_goja": r"C:\Users\kursu\Downloads\Telegram Desktop\Go'ja.jpg",
    "dish_lagmon": r"C:\Users\kursu\Downloads\Telegram Desktop\Lagmon.jpg",
    "dish_sabzavotd": r"C:\Users\kursu\Downloads\Telegram Desktop\Sabzavotli dolma.jpg",
    "dish_mantilishorva": r"C:\Users\kursu\Downloads\Telegram Desktop\Mantili shorva.jpg",
    "dish_firkadelkali": r"C:\Users\kursu\Downloads\Telegram Desktop\Firkadelkali shorva.jpg",
    "dish_kosadimlama": r"C:\Users\kursu\Downloads\Telegram Desktop\Kosa dimlama.jpg",
    "dish_tuxumdolma": r"C:\Users\kursu\Downloads\Telegram Desktop\Tuxum dolma.jpg",
    "dish_mastava": r"C:\Users\kursu\Downloads\Telegram Desktop\Mastava.jpg",
    "dish_chuchvara": r"C:\Users\kursu\Downloads\Telegram Desktop\Chuchvara.jpg",
    "dish_andijonmanti": r"C:\Users\kursu\Downloads\Telegram Desktop\Andijon manti.jpg",
    "dish_spagetti": r"C:\Users\kursu\Downloads\Telegram Desktop\Spagetti.jpg",
    "dish_qovurmala": r"C:\Users\kursu\Downloads\Telegram Desktop\Qovurma lag'mon.jpg",
    "dish_dimlama": r"C:\Users\kursu\Downloads\Telegram Desktop\Dimlama.jpg",
    "dish_beshbarmoq": r"C:\Users\kursu\Downloads\Telegram Desktop\Besh barmoq.jpg",
    "dish_bibimbap": r"C:\Users\kursu\Downloads\Telegram Desktop\Bibimbap.jpg",
    "dish_quyuqdolma": r"C:\Users\kursu\Downloads\Telegram Desktop\Do'lma.jpg",
    "dish_choyxona": r"C:\Users\kursu\Downloads\Telegram Desktop\Choyxona palov.jpg",
    "dish_gulxonim": r"C:\Users\kursu\Downloads\Telegram Desktop\Gulxonim.jpg",
    "dish_bayramona": r"C:\Users\kursu\Downloads\Telegram Desktop\Bayramona osh va ayron.jpg",
    "dish_grechkapalov": r"C:\Users\kursu\Downloads\Telegram Desktop\Grechka palov.jpg",
    "dish_turkcharatatuy": r"C:\Users\kursu\Downloads\Telegram Desktop\Turkcha ratatuy.jpg",
    "dish_balish": r"C:\Users\kursu\Downloads\Telegram Desktop\Balish.jpg",
    "dish_goshlirulet": r"C:\Users\kursu\Downloads\Telegram Desktop\Go'shli rulet.jpg",
    "dish_shivit": r"C:\Users\kursu\Downloads\Telegram Desktop\Shivit oshi.jpg",
    "dish_nonpalov": r"C:\Users\kursu\Downloads\Telegram Desktop\Non palov.jpg",
    "dish_kartoshkadolma": r"C:\Users\kursu\Downloads\Telegram Desktop\Kartoshka do'lma.jpg",
    "dish_dumbulpalov": r"C:\Users\kursu\Downloads\Telegram Desktop\Dumbul palov.jpg",
    "dish_teftel": r"C:\Users\kursu\Downloads\Telegram Desktop\Teftel.jpg",
    "dish_sarimsoqli": r"C:\Users\kursu\Downloads\Telegram Desktop\Sarimsoqli kartoshka.jpg",
    "dish_begodi": r"C:\Users\kursu\Downloads\Telegram Desktop\Begodi.jpg",
    "dish_baliqlikotlet": r"C:\Users\kursu\Downloads\Telegram Desktop\Baliqli kotlet.jpg",
    "dish_jigarkabob": r"C:\Users\kursu\Downloads\Telegram Desktop\Jigar kabob.jpg",
    "dish_qozonkabob": r"C:\Users\kursu\Downloads\Telegram Desktop\Qozon kabob.jpg",
    "dish_qiymalikabob": r"C:\Users\kursu\Downloads\Telegram Desktop\Qiymali kabob.jpg",
    "dish_tandirkabob": r"C:\Users\kursu\Downloads\Telegram Desktop\Tandir kabob.jpg",
    "dish_tovuqkabob": r"C:\Users\kursu\Downloads\Telegram Desktop\Tovuq kabob.jpg",
    "dish_namangankabob": r"C:\Users\kursu\Downloads\Telegram Desktop\Namangan kabob.jpg",
    "dish_norin": r"C:\Users\kursu\Downloads\Telegram Desktop\Norin.jpg",
    "dish_xasip": r"C:\Users\kursu\Downloads\Telegram Desktop\Xasip.jpg",
    "dish_tuxumbarak": r"C:\Users\kursu\Downloads\Telegram Desktop\Tuxum Barak.jpg",
    "dish_achchiqchuchuk": r"C:\Users\kursu\Downloads\Telegram Desktop\Achchiqchuchuksalat.jpg",
    "dish_bodringbrinza": r"C:\Users\kursu\Downloads\Telegram Desktop\Bodring va brinzali salat.jpg",
    "dish_karampomidor": r"C:\Users\kursu\Downloads\Telegram Desktop\Karam va pomidorli salat.jpg",
    "dish_gruzincha": r"C:\Users\kursu\Downloads\Telegram Desktop\Gruzincha salat.jpg",
    "dish_qarsildoq": r"C:\Users\kursu\Downloads\Telegram Desktop\Qarsildoq salat.jpg",
    "dish_suzmali": r"C:\Users\kursu\Downloads\Telegram Desktop\Suzmali salat.jpg",
    "dish_penchuza": r"C:\Users\kursu\Downloads\Telegram Desktop\Penchuza salat.jpg",
    "dish_mandarin": r"C:\Users\kursu\Downloads\Telegram Desktop\Mandarin salat.jpg",
    "dish_tovuqlisalat": r"C:\Users\kursu\Downloads\Telegram Desktop\Tovuqli salat.jpg",
    "dish_smak": r"C:\Users\kursu\Downloads\Telegram Desktop\Smak salat.jpg",
    "dish_ozdiruvchi": r"C:\Users\kursu\Downloads\Telegram Desktop\Ozdiruvchi salat.jpg",
    "dish_mevali": r"C:\Users\kursu\Downloads\Telegram Desktop\Mevali salat.jpg",
    "dish_braslet": r"C:\Users\kursu\Downloads\Telegram Desktop\Braslet salat.jpg",
    "dish_qotgannonli": r"C:\Users\kursu\Downloads\Telegram Desktop\Qotgan nonli salat.jpg",
    "dish_goshtlisa": r"C:\Users\kursu\Downloads\Telegram Desktop\Go'shtli salat.jpg",
    "dish_karamli": r"C:\Users\kursu\Downloads\Telegram Desktop\Karamli salat.jpg",
    "dish_olivye": r"C:\Users\kursu\Downloads\Telegram Desktop\Olivye.jpg",
    "dish_tovuqiolivye": r"C:\Users\kursu\Downloads\Telegram Desktop\Tovuqli olivye.jpg",
    "dish_bodringsalat": r"C:\Users\kursu\Downloads\Telegram Desktop\Bodring salat.jpg",
    "dish_shanxay": r"C:\Users\kursu\Downloads\Telegram Desktop\Shanxaycha salat.jpg",
    "dish_qushuyali": r"C:\Users\kursu\Downloads\Telegram Desktop\Qush uyali salat.jpg",
    "dish_toshkentsalat": r"C:\Users\kursu\Downloads\Telegram Desktop\Toshkentcha salat.jpg",
    "dish_portobello": r"C:\Users\kursu\Downloads\Telegram Desktop\Portobello salat.jpg",
    "dish_ananas": r"C:\Users\kursu\Downloads\Telegram Desktop\Ananas va tovuqli salat.jpg",
    "dish_sezar": r"C:\Users\kursu\Downloads\Telegram Desktop\Sezar salat.jpg",
    "dish_bodringkaram": r"C:\Users\kursu\Downloads\Telegram Desktop\Bodring va karamli salat.jpg",
    "dish_turkchaburek": r"C:\Users\kursu\Downloads\Telegram Desktop\Turkcha burek.jpg",
    "dish_goshtlisomsa": r"C:\Users\kursu\Downloads\Telegram Desktop\Go’shtli somsa.jpg",
    "dish_yupqa": r"C:\Users\kursu\Downloads\Telegram Desktop\Yupqa.jpg",
    "dish_qiymaliquymoq": r"C:\Users\kursu\Downloads\Telegram Desktop\Qiymali quymoq.jpg",
    "dish_pishloqlicheburek": r"C:\Users\kursu\Downloads\Telegram Desktop\Pishloqli cheburek.jpg",
    "dish_gumma": r"C:\Users\kursu\Downloads\Telegram Desktop\Gumma.jpg",
    "dish_pahlava": r"C:\Users\kursu\Downloads\Telegram Desktop\Pahlava.jpg",
    "dish_chakchak": r"C:\Users\kursu\Downloads\Telegram Desktop\Chak-chak.jpg",
    "dish_turkchapishiriq": r"C:\Users\kursu\Downloads\Telegram Desktop\Turkcha pishiriq.jpg",
    "dish_qozonsomsa": r"C:\Users\kursu\Downloads\Telegram Desktop\Qozon somsa.jpg",
    "dish_sabzavotlisomsa": r"C:\Users\kursu\Downloads\Telegram Desktop\Sabzavotli somsa.jpg",
    "dish_yuraksomsa": r"C:\Users\kursu\Downloads\Telegram Desktop\Yurak somsa.jpg",
    "dish_qatlamasomsa": r"C:\Users\kursu\Downloads\Telegram Desktop\Qatlama somsa.jpg",
    "dish_nisholda": r"C:\Users\kursu\Downloads\Telegram Desktop\Nisholda.jpg",
    "dish_holvetar": r"C:\Users\kursu\Downloads\Telegram Desktop\Holvetar.jpg",
    "dish_tvaroglikr": r"C:\Users\kursu\Downloads\Telegram Desktop\Tvaroglikrendel.jpg",
    "dish_shokoglazur": r"C:\Users\kursu\Downloads\Telegram Desktop\Shokoladli glazur.jpg",
    "dish_bananlieskimo": r"C:\Users\kursu\Downloads\Telegram Desktop\Bananli eskimo.jpg",
    "dish_jemlipirog": r"C:\Users\kursu\Downloads\Telegram Desktop\Jemli pirog.jpg",
    "dish_tvoroglibulochka": r"C:\Users\kursu\Downloads\Telegram Desktop\Tvaroglibulochka.jpg",
    "dish_malinalichizkeyk": r"C:\Users\kursu\Downloads\Telegram Desktop\Malinali chizkeyk.jpg",
    "dish_bolqaymoq": r"C:\Users\kursu\Downloads\Telegram Desktop\Bolqaymoq.jpg",
    "dish_murabbolipirog": r"C:\Users\kursu\Downloads\Telegram Desktop\Murabboli pirog.jpg",
    "dish_asallipirojniy": r"C:\Users\kursu\Downloads\Telegram Desktop\Asalli pirojniy.jpg",
    "dish_shaftolilimizq": r"C:\Users\kursu\Downloads\Telegram Desktop\Shaftolili muzqaymoq.jpg",
    "dish_aylanay": r"C:\Users\kursu\Downloads\Telegram Desktop\Aylanay pirogi.jpg",
    "dish_chumoliuya": r"C:\Users\kursu\Downloads\Telegram Desktop\Chumoli uyasi.jpg",
    "dish_olchali": r"C:\Users\kursu\Downloads\Telegram Desktop\Olchali pirog.jpg",
    "dish_shokokeks": r"C:\Users\kursu\Downloads\Telegram Desktop\Shokoladli keks.jpg",
    "dish_asallipechenye": r"C:\Users\kursu\Downloads\Telegram Desktop\Asalli pechenye.jpg",
    "drink_olmali": r"C:\Users\kursu\Downloads\Telegram Desktop\Olmali choy.jpg",
    "drink_namatak": r"C:\Users\kursu\Downloads\Telegram Desktop\Namatak sharbati.jpg",
    "drink_yalpizlimon": r"C:\Users\kursu\Downloads\Telegram Desktop\Yalpizli limon choy.jpg",
    "drink_qulupnay": r"C:\Users\kursu\Downloads\Telegram Desktop\Qulupnayli ichimlik.jpg",
    "drink_qovun": r"C:\Users\kursu\Downloads\Telegram Desktop\Qovun sharbati.jpg",
    "drink_bodomli": r"C:\Users\kursu\Downloads\Telegram Desktop\Bodomli sut.jpg",
    "drink_uzum": r"C:\Users\kursu\Downloads\Telegram Desktop\Uzum sharbati.jpg",
    "drink_mevali": r"C:\Users\kursu\Downloads\Telegram Desktop\Mevali sharbat.jpg",
    "drink_qatiq": r"C:\Users\kursu\Downloads\Telegram Desktop\Qatiq.jpg",
    "drink_tarvuz": r"C:\Users\kursu\Downloads\Telegram Desktop\Tarvuz sharbati.jpg",
    "drink_sabzi": r"C:\Users\kursu\Downloads\Telegram Desktop\Sabzi sharbati.jpg",
    "drink_zira": r"C:\Users\kursu\Downloads\Telegram Desktop\Zira choy.jpg",
    "drink_vitaminli": r"C:\Users\kursu\Downloads\Telegram Desktop\Vitaminli ichimlik.jpg",
    "drink_moxito": r"C:\Users\kursu\Downloads\Telegram Desktop\Moxito.jpg",
    "tort_praga": r"C:\Users\kursu\Downloads\Telegram Desktop\Praga torti.jpg",
    "tort_napaleon": r"C:\Users\kursu\Downloads\Telegram Desktop\Napaleon torti.jpg",
    "tort_zebra": r"C:\Users\kursu\Downloads\Telegram Desktop\Zebra torti.jpg",
    "tort_pancho": r"C:\Users\kursu\Downloads\Telegram Desktop\Pancho torti.jpg",
    "tort_medovik": r"C:\Users\kursu\Downloads\Telegram Desktop\Medovik torti.jpg",
    "tort_frezye": r"C:\Users\kursu\Downloads\Telegram Desktop\Frezye torti.jpg",
    "tort_karamel": r"C:\Users\kursu\Downloads\Telegram Desktop\Karamel torti.jpg",
    "tort_kitakat": r"C:\Users\kursu\Downloads\Telegram Desktop\Kita-kat torti.jpg",
    "tort_boston": r"C:\Users\kursu\Downloads\Telegram Desktop\Bostoncha kremli tort.jpg",
    "tort_bounty": r"C:\Users\kursu\Downloads\Telegram Desktop\Bounty torti.jpg",
    "tort_pavlova": r"C:\Users\kursu\Downloads\Telegram Desktop\Pavlova torti.jpg",
    "non_qatlamapatir": r"C:\Users\kursu\Downloads\Telegram Desktop\Qatlama patir.jpg",
    "non_shirinkulcha": r"C:\Users\kursu\Downloads\Telegram Desktop\Shirin kulcha.jpg",
    "non_moychechak": r"C:\Users\kursu\Downloads\Telegram Desktop\Moychechak non.jpg",
    "non_goshtli": r"C:\Users\kursu\Downloads\Telegram Desktop\Go’shtli non.jpg",
    "non_patir": r"C:\Users\kursu\Downloads\Telegram Desktop\Patir.jpg",
    "non_lochira": r"C:\Users\kursu\Downloads\Telegram Desktop\Lochira patir.jpg",
    "non_obinon": r"C:\Users\kursu\Downloads\Telegram Desktop\Obi non.jpg",
    "non_qatlama": r"C:\Users\kursu\Downloads\Telegram Desktop\Qatlama.jpg",
    "non_jizzali": r"C:\Users\kursu\Downloads\Telegram Desktop\Jizzali patir.jpg"
}
